# Generated by Django 4.1.5 on 2023-01-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tag_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag__name'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статьи'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
