# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "Датчик соседа",
  "description": "Необходимо отдать"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/14/
Content-Type: application/json

{
  "name": "Ванна"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 14,
  "temperature": 6
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/14/
Content-Type: application/json
