# Generated by Django 4.1.4 on 2022-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=20)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
    ]
